version: '3'
services:
  api:
    build: ./frontdesk-backend
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    ports:
      - '9000:9000'
    volumes:
      - ./frontdesk-backend:/api
      - /api/node_modules
    depends_on:
      - db
    container_name: frontdesk-api
  # client:
  #   build: ./frontdesk-frontend
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./frontdesk-frontend:/client
  #     - /client/node_modules
  #   container_name: frontdesk-client
  db:
    image: mongo
    ports:
      - '27017:27017'
    container_name: frontdesk-db
    volumes:
      - ./mongo/data:/data/db
  # backup:
  #   build: ./backup
  #   container_name: frontdesk-backup
  #   volumes:
  #     - ./backup/data:/backup/
