version: "3"
services:
  api:
    build: ./frontdesk-backend
    environment: 
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontdesk-backend:/api
      - /api/node_modules
    depends_on:
      - db
    container_name: frontdesk-api
  # client:
  #   build: ./frontdesk-frontend
  #   environment: 
  #     - CHOKIDAR_USEPOLLING=true
  #   volumes:
  #     - ./frontdesk-frontend:/client
  #     - /client/node_modules
  #   container_name: frontdesk-client
  db:
    image: mongo
    container_name: frontdesk-db
    volumes: 
      - ./mongo/data:/data/db
  nginx:
    depends_on:
        - api
    restart: always
    build: ./nginx
    ports:
        - "80:80"
  backup:
    build: ./backup
    container_name: frontdesk-backup
    volumes:
      - ./backup/data:/backup/